---
title: "Coronavirus Dashboard" 
Author: "GB"
output: html_document
---

```{r echo=FALSE, include=FALSE}
library(RSocrata)
library(tidyverse)
library(lubridate)
library(data.table)
```


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# this is the socrata connection
g<-read.socrata("https://data.cdc.gov/resource/9mfq-cb36.json", app_token = "du1xYluz5Q3hWLPoeoxced3Dg", stringsAsFactors = FALSE)
# data is imported as characters following syntax converst to numeric
g$tot_death=as.numeric(g$tot_death)
g$new_death=as.numeric(g$new_death)
g$new_case=as.numeric(g$new_case)
```

### This is the covid new cases chart
Analysis is linked to cdc website via socrata and will update when script is run

```{r echo=TRUE, include=TRUE}
ma<- g %>%
    filter(state=="MA") %>%
    filter(as.Date(submission_date)>"2020-05-22")%>%
    select(submission_date, tot_death, new_case, new_death) %>%
    rename("total_deaths"=tot_death, "date"= submission_date)

ggplot(ma, aes(date, new_case))+
    geom_line()+
    theme_classic()
```

### MA New cases
following shows new cases for massachusetts trailing 30 days

```{r, echo=TRUE}
matrail<- g %>%
    filter(state=="MA") %>%
    filter(as.Date(submission_date)>Sys.Date()-30)%>%
    select(submission_date, tot_death, new_case, new_death) %>%
    rename("total_deaths"=tot_death, "date"= submission_date)

ggplot(matrail, aes(date, new_case))+
    geom_line()+
    geom_point(color="red")+
    labs(title = "MA New Cases Trailing 30")+
    scale_x_datetime(date_breaks = "day", date_labels = "%d")+
    theme_classic()


```



## Plot for new deaths

```{r echo=TRUE}
deathtrail<- g %>%
    filter(state=="MA") %>%
    filter(as.Date(submission_date)>Sys.Date()-30)%>%
    select(submission_date, tot_death, new_case, new_death, ) %>%
    rename("total_deaths"=tot_death, "date"= submission_date)

ggplot(deathtrail, aes(date, new_death))+
    geom_line()+
    geom_point(color="red")+
    theme_classic()+
    scale_x_datetime(date_breaks = "day", date_labels = "%d")+
    theme_classic()+
    labs(title = "MA Deaths Trailing 30")
```
```{r}
view(g)

glimpse(g)
```

